// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyVatTuPhongMay.Data;

#nullable disable

namespace QuanLyVatTuPhongMay.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.LichSuDangNhap", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiDiemDN")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiDiemDX")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("LichSuDangNhap", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.LichThucHanh", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLich"));

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKT")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLich");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("LichThucHanh", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.LichTruc", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLich"));

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<int>("MaPhongMay")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngay")
                        .HasColumnType("date");

                    b.HasKey("MaLich");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaPhongMay");

                    b.ToTable("LichTruc", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.Loai", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoai");

                    b.ToTable("Loai", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.Lop", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLop"));

                    b.Property<string>("TenLop")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLop");

                    b.ToTable("Lop", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNV");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.NhatKyThayDoi", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKy"));

                    b.Property<int?>("MaLichSu")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThongTinCu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThongTinMoi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("MaLichSu");

                    b.ToTable("NhatKyThayDoi", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.PhongMay", b =>
                {
                    b.Property<int>("MaPhongMay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhongMay"));

                    b.Property<string>("TenPhongMay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhongMay");

                    b.ToTable("PhongMay", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.ThuongHieu", b =>
                {
                    b.Property<int>("MaThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThuongHieu"));

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaThuongHieu");

                    b.ToTable("ThuongHieu", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.TrangTB", b =>
                {
                    b.Property<int>("MaTTB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTTB"));

                    b.Property<int?>("GiaTien")
                        .HasColumnType("int");

                    b.Property<int?>("MaLich")
                        .HasColumnType("int");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhongMay")
                        .HasColumnType("int");

                    b.Property<int?>("MaThuongHieu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("date");

                    b.Property<int?>("SoLanSua")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTTB");

                    b.HasIndex("MaLich");

                    b.HasIndex("MaLoai");

                    b.HasIndex("MaPhongMay");

                    b.HasIndex("MaThuongHieu");

                    b.ToTable("TrangTB", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.LichSuDangNhap", b =>
                {
                    b.HasOne("QuanLyVatTuPhongMay.Models.NguoiDung", "NguoiDung")
                        .WithMany("LichSuDangNhaps")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.LichThucHanh", b =>
                {
                    b.HasOne("QuanLyVatTuPhongMay.Models.NguoiDung", "NguoiDung")
                        .WithMany("LichThucHanhs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.LichTruc", b =>
                {
                    b.HasOne("QuanLyVatTuPhongMay.Models.NhanVien", "NhanVien")
                        .WithMany("LichTrucs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyVatTuPhongMay.Models.PhongMay", "PhongMay")
                        .WithMany("LichTrucs")
                        .HasForeignKey("MaPhongMay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("PhongMay");
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.NhatKyThayDoi", b =>
                {
                    b.HasOne("QuanLyVatTuPhongMay.Models.LichSuDangNhap", "LichSuDangNhap")
                        .WithMany("NhatKyThayDois")
                        .HasForeignKey("MaLichSu")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LichSuDangNhap");
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.TrangTB", b =>
                {
                    b.HasOne("QuanLyVatTuPhongMay.Models.LichThucHanh", "LichThucHanh")
                        .WithMany("TrangTBs")
                        .HasForeignKey("MaLich")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyVatTuPhongMay.Models.Loai", "Loai")
                        .WithMany("TrangTBs")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyVatTuPhongMay.Models.PhongMay", "PhongMay")
                        .WithMany("TrangTBs")
                        .HasForeignKey("MaPhongMay")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyVatTuPhongMay.Models.ThuongHieu", "ThuongHieu")
                        .WithMany("TrangTBs")
                        .HasForeignKey("MaThuongHieu")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LichThucHanh");

                    b.Navigation("Loai");

                    b.Navigation("PhongMay");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.LichSuDangNhap", b =>
                {
                    b.Navigation("NhatKyThayDois");
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.LichThucHanh", b =>
                {
                    b.Navigation("TrangTBs");
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.Loai", b =>
                {
                    b.Navigation("TrangTBs");
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.NguoiDung", b =>
                {
                    b.Navigation("LichSuDangNhaps");

                    b.Navigation("LichThucHanhs");
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.NhanVien", b =>
                {
                    b.Navigation("LichTrucs");
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.PhongMay", b =>
                {
                    b.Navigation("LichTrucs");

                    b.Navigation("TrangTBs");
                });

            modelBuilder.Entity("QuanLyVatTuPhongMay.Models.ThuongHieu", b =>
                {
                    b.Navigation("TrangTBs");
                });
#pragma warning restore 612, 618
        }
    }
}
